### ISSUE TITLE
Changing font size doesn't work with SVGR and Tailwind

### ISSUE THREAD

**Issue by da-kicks-87** [marella/material-symbols#13]
Hello,

I am able to import the svgs as React components into my Next.js App via SVGR.  They render in the browser.

I am having problem changing the size of the icons by font size.

I have added this to my global css to change the icons by font size:

```svg {
    width: 1rem;
    height: 1rem;
    fill: currentColor;
  }```

I then call the components with Tailwindcss class like this:
`<Face className="text-8xl" />`

In the browser the Face icon gets cropped and is not the correct size.

Any ideas why?

**Comment by marella** [comment]
Hi,

You should use `em` not `rem` to change size by font size as mentioned [here](https://github.com/marella/material-symbols/tree/main/svg/400#styling):

```css
svg {
  width: 1em;
  height: 1em;
  fill: currentColor;
}
```

**Comment by da-kicks-87** [comment]
Hi yes, you are right, using em units should be used in order to change its' size by font size. I am more accustomed to using mostly rem units because Tailwind and other CSS frameworks use them.

Anways I have also tried with em units as in your example. More of the icon is shown, but still a cropping problem.

React compoents with Tailwind font classes. 

`<Face className="text-3xl" />
<Star className="text-3xl" />
`
Screenshot of the crop: 

![Screenshot 2023-01-15 123100](https://user-images.githubusercontent.com/70115804/212557012-40dfda8e-33e8-40df-83d9-0f27a269eaea.jpg)



Could it be that  svg themselfs  are not optimized?

**Comment by marella** [comment]
Are you using the latest version of material-symbols? Similar [issue](https://github.com/marella/material-symbols/issues/5) used to be present in older versions (< 0.4.0) due to SVGs missing viewBox property.

**Comment by da-kicks-87** [comment]
I have installed the `material-symbols/svg-400` package. I only need the svgs. It is the latest version `0.4.2`

I have inspected the react rendered svgs, they don't have the viewBox property.

**Comment by da-kicks-87** [comment]
I have compared the SVG code from this repo the the SVGs that are rendered on my app. In this repo the SVGs do have the viewBox attribute, but when they are rendered on my App with SVGR they are missing the viewBox attribute.

This would be an issue with SVGR then?

**Comment by marella** [comment]
Sorry for the late response. I think SVGR uses SVGO under the hood which removes viewBox by default. You can disable `removeViewBox` plugin in your SVGO config.
Please see SVGO [README](https://github.com/svg/svgo#svg-wont-scale-when-css-is-applied-on-it) and this [issue](https://github.com/svg/svgo/issues/1128) for more info.

**Comment by MaKTaiL** [comment]
I'm having a hard time adjusting the size of these icons. I changed to 'em' instead of 'rem' and it is still not working. I don't know what to do honestly.

**Comment by markomitranic** [comment]
So, its quite simple - it depends on how you include the CSS.
In Tailwind, you can use layers in order to override the default cascade behaviour.

In my case, I just had to move the material font declaration block into my `@layer base` like this:

```css
@layer base {
  /** 
  * Material Symbols Sharp Icons
  * We import this font from Google Fonts in order to minimize the font size.
  * Selected options:
  * - opsz: 24
  * - wght: 600
  * - FILL: 0
  * - GRAD: 0
  *
  * @see https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp:opsz,wght,FILL,GRAD@24,600,0,0
  */
  @font-face {
    font-family: "Material Symbols Sharp";
    font-style: normal;
    font-weight: 600;
    src: url(https://fonts.gstatic.com/s/materialsymbolssharp/v228/gNNBW2J8Roq16WD5tFNRaeLQk6-SHQ_R00k4c2_whPnoY9ruReaU4bHmz74m0ZkGH-VBYe1x0TV6x4yFH8F-H5OdzEL3sVTgJtfbYxNVpTCLJ1H7-0Hk.woff2)
      format("woff2");
  }
  .material-symbols-sharp {
    font-family: "Material Symbols Sharp";
    font-weight: normal;
    font-style: normal;
    font-size: 24px;
    line-height: 1;
    letter-spacing: normal;
    text-transform: none;
    display: inline-block;
    white-space: nowrap;
    word-wrap: normal;
    direction: ltr;
    -webkit-font-feature-settings: "liga";
    -webkit-font-smoothing: antialiased;
  }
}
```

After doing so, the `text-xs` classname on the individual components automatically starts working fine, as the base class is now considered a base style. :)
